### ISSUE TITLE
iOS support (Jailbroken Only)

### ISSUE THREAD

**Issue by joeyoropesa-dev** [zheka2304/innercore-mod-toolchain#8]
Can you make this app for iOS that are jailbroken so we can experience Inner Core mods on iOS devices as well

**Comment by Molybdocene-dichloride** [comment]
Inner Core will not be ported to IOS because there is a different way of Minecraft Bedrock Edition patching on Android and IOS and Zheka Smirnov will not waste time on this, he does other things - Bug fixing after porting to Minecraft 1.16 and maybe server core.
Also jailbreaked devices is few counted.
